name: Sanitize notebooks

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write  # needed to push fixes

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run sanitizer (keep outputs)
        run: |
          python sanitize_ipynb.py
        # Pokud chceš na GitHubu vždy čistý preview bez výstupů, zvol variantu:
        # run: python sanitize_ipynb.py --strip-outputs

      - name: Commit & push changes (if any)
        if: failure()  # our script exits 2 when it made changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: sanitize notebooks for GitHub preview"
          git push
